### ISSUE TITLE
Homepage field normalization

### ISSUE THREAD

**Issue by dptoot** [sindresorhus/write-pkg#10]
Thanks for the (and hundreds of other utils)

Create-react-app uses the homepage field for resource path generation.  Our application is looking to use relative paths for our static resources but write-pkg seems to be assuming http: and pre-pending it to the homepage value.

```sh
-  "homepage": "./",
+  "homepage": "http://./",
```

Any possibility of allowing relative paths here if no protocol is specified?

**Comment by sindresorhus** [comment]
This package doesn't normalize the fields. Do you mean [`read-pkg`](https://github.com/sindresorhus/read-pkg)?

> Create-react-app uses the homepage field for resource path generation. Our application is looking to use relative paths for our static resources but write-pkg seems to be assuming http: and pre-pending it to the homepage value.

The `homepage` field is intended to be an absolute URL. It's unfortunate the `create-react-app` overloads it to mean something different. You should open an issue on `create-react-app` about this. They should use a custom field instead.

**Comment by dptoot** [comment]
Thanks for the quick response.  I will investigate.  Perhaps I am the one overloading in that case.
