### ISSUE TITLE
Persist unchanged dependencies

### ISSUE THREAD

**Issue by maticzav** [sindresorhus/write-pkg#13]
Is it possible to only override the selected dependencies without removing unlisted ones?

**Comment by sindresorhus** [comment]
I don't understand what you're asking. Can you provide an example or elaborate?

**Comment by sindresorhus** [comment]
Yeah, we could expose some utility methods for common package.json modification needs, like `writePkg.addDependencies([{name: 'a', version: '1.0.0', type: 'dev'}]);`, `writePkg.removeDependencies(['b']);`.

**Comment by tommy-mitchell** [comment]
@sindresorhus should consecutive calls be able to preserve arbitrary fields in a `package.json`? e.g:

```js
await writePackage({name: 'foo', version: '1.0.0'});
```

```json
{
	"name": "foo",
	"version": "1.0.0"
}
```

```js
await writePackage({version: '2.0.0', license: "MIT"});
```

```json
{
	"name": "foo",
	"version": "2.0.0",
	"license": "MIT"
}
```

---

Currently, `package.json` after the second call would be:

```json
{
	"version": "2.0.0",
	"license": "MIT"
}
```

I had been trying to use `write-pkg` to test `np` this way, since I (incorrectly) assumed from this line in the readme that this was already the actual behavior:

> Preserves the indentation if the file already exists.

Maybe the current behavior could be moved to an `overwritePackage` function?

**Comment by sindresorhus** [comment]
No, I would expect `writePackage` to overwrite. We could instead add a `updatePackage` method for merging.

**Comment by tommy-mitchell** [comment]
Thinking it over more, `updatePackage` could take the place of `addPackageDependency`. If someone wanted to remove a dependency, they could use a combination of `read-pkg` and `dot-prop`, or something similar.

**Comment by sindresorhus** [comment]
I stil think `addPackageDependency` would be a nice convenience.

**Comment by sindresorhus** [comment]
> addPackageDependency could easily be a wrapper around updatePackage.

Yep

> What about removePackageDependency thought? Would we want to include that?

Makes sense to have the inverse of adding, yes.
