### ISSUE TITLE
Sorting keys in dependencies

### ISSUE THREAD

**Issue by zkochan** [sindresorhus/write-pkg#2]
Hey, we use this lib currently in [pnpm](https://github.com/pnpm/pnpm) but we sort the keys in the dependencies, devDependencies, optionalDependencies properties before passing `package.json` to write-pkg ([see](https://github.com/pnpm/pnpm/blob/master/src/save.ts#L15)). IMHO, this should be done inside `write-pkg`, as this is a general convention in package.json files.

Would you accept a PR that would add this to write-pkg?

**Comment by sindresorhus** [comment]
👍 Good idea. PR more than welcome :)

I have a module you could use for this: https://github.com/sindresorhus/sort-keys

**Comment by zkochan** [comment]
@sindresorhus PR is ready. Would you please review it?
