### ISSUE TITLE
Removing empty dependencies properties

### ISSUE THREAD

**Issue by zkochan** [sindresorhus/write-pkg#4]
Would you accept a PR that would remove empty dependencies fields before saving the file.

So

```json
{
  "name": "foo",
  "version": "1.0.0",
  "dependencies": {}
}
```

would be saved as 

```json
{
  "name": "foo",
  "version": "1.0.0"
}
```

Empty `dependencies`, `devDependencies`, `optionalDependencies`, `peerDependencies` would be removed.

**Comment by clemtrek** [comment]
I have the problem in Lerna.
