### ISSUE TITLE
Maintain package.json indentation

### ISSUE THREAD

**Issue by yatharthk** [sindresorhus/write-pkg#7]
Original issue: [avajs/ava](https://github.com/avajs/ava/issues/1358).

**Comment by kevva** [comment]
Well, I imagine you'd need to provide the indentation to this module, rather than detecting it here because all we get is parsed JSON which doesn't preserve the original indentation.

**Comment by sindresorhus** [comment]
If `auto` is set we could try to read the file before reading and if it exists, detect the indentation.

**Comment by yatharthk** [comment]
Actually, why do we even need to set `auto`? We can always do the check if file already exists; and maintain indent if it does.

**Comment by sindresorhus** [comment]
@yatharthk I meant, we implement the `auto` option in `write-json-file` and use it here. Detecting indentation comes with some overhead, so it shouldn't be default in `write-json-file`, but it can just be the default behavior here without any option.

**Comment by zkochan** [comment]
@sindresorhus a PR is ready for this feature
