### ISSUE TITLE
Option to disable normalization

### ISSUE THREAD

**Issue by novemberborn** [sindresorhus/write-pkg#9]
#4 means that, when `ava --init` is used, empty `dependencies` objects are removed. I think `ava --init` should be additive and not modify anything else in the `package.json`.

See https://github.com/avajs/ava/issues/1567.

**Comment by sindresorhus** [comment]
Yeah, could be a `normalize: false` option.

**Comment by zkochan** [comment]
Well, might be a better idea to name the option `keepEmptyDependencies` as normalize `package.json` means a lot more manipulations.

https://github.com/npm/normalize-package-data#what-normalization-currently-entails

**Comment by evocateur** [comment]
`write-pkg` has never claimed to (nor should it, imo) do all the things `normalize-package-data` does, however.

**Comment by TheDancingCode** [comment]
I wouldn't mind implementing this. Would it be a third argument?
